<a href="https://colab.research.google.com/github/gaeunfalo16/Deep_Learning/blob/master/training_and_test_dataset.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import tensorflow as tf

#training data
x_data = [[1, 2, 1], [1, 3, 2], [1, 3, 4], [1, 5, 5], [1, 7, 5], [1, 2, 5], [1, 6, 6], [1, 7, 7]]
y_data = [[0, 0, 1], [0, 0, 1], [0, 0, 1], [0, 1, 0], [0, 1, 0], [0, 1, 0], [1, 0, 0], [1, 0, 0]]

#test data
x_test = [[2, 1, 1], [3, 1, 2], [3, 3, 4]]
y_test = [[0, 0, 1], [0, 0, 1], [0, 0, 1]]

#placeholder to be fed
X = tf.placeholder("float", [None, 3])
Y = tf.placeholder("float", [None, 3])

#weight and bias
W = tf.Variable(tf.random_normal([3, 3]))
b = tf.Variable(tf.random_normal([3]))

#hypothesis and cost
hypothesis = tf.nn.softmax(tf.matmul(X, W) + b)
cost = -tf.reduce_mean(tf.reduce_sum(tf.log(hypothesis) * Y, axis = 1))
optimizer = tf.train.GradientDescentOptimizer(learning_rate = 0.1).minimize(cost)

#Correct prediction test model
#Select max value from the each row of hypothesis array
prediction = tf.arg_max(hypothesis, 1)
is_correct = tf.equal(prediction, tf.arg_max(Y, 1))
accuracy = tf.reduce_mean(tf.cast(is_correct, tf.float32))

#Launch the graph
with tf.Session() as sess :
  #Initialize tensorflow variable
  sess.run(tf.global_variables_initializer())
  for step in range(201) :
    cost_val, W_val, _ = sess.run([cost, W, optimizer], feed_dict = {X: x_data, Y: y_data})
    print(step, cost_val, W_val)

  #predict
  print("Prediction : ", sess.run(prediction, feed_dict = {X: x_test}))
  #Calculate the accuracy
  print("Accuracy : ", sess.run(accuracy, feed_dict = {X: x_test, Y: y_test}))







0 2.4082584 [[ 0.04573796 -0.6168097  -0.0241928 ]
 [ 0.13861944 -0.5975595   1.0579782 ]
 [-0.05750476  1.1899773  -0.7283668 ]]
1 1.6323028 [[ 0.06342768 -0.6369043  -0.02178794]
 [ 0.27557155 -0.67448425  0.99795073]
 [ 0.0836877   1.084204   -0.7637859 ]]
2 1.2088568 [[ 0.05854661 -0.63935643 -0.01445472]
 [ 0.295506   -0.65795004  0.96148205]
 [ 0.11392934  1.0733775  -0.7832011 ]]
3 1.1885635 [[ 0.04722865 -0.6406716  -0.00182161]
 [ 0.27997938 -0.635389    0.95444757]
 [ 0.11213028  1.0695821  -0.7776066 ]]
4 1.1775382 [[ 0.03925001 -0.6445529   0.01003831]
 [ 0.2823167  -0.62687546  0.94359666]
 [ 0.12724344  1.0517097  -0.77484727]]
5 1.1670642 [[ 0.02916498 -0.6467847   0.02235514]
 [ 0.27291453 -0.6096704   0.93579376]
 [ 0.13082722  1.0429906  -0.769712  ]]
6 1.15694 [[ 0.02058765 -0.65010333  0.0342511 ]
 [ 0.27144018 -0.5985461   0.92614377]
 [ 0.14173892  1.0283293  -0.7659623 ]]
7 1.1470599 [[ 0.01112182 -0.65266985  0.04628347]
 [ 0.264883   -0.5835978   0.9177526 ]
 [